version: '3.8'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:latest
    links:
      - postgres
    ports:
      - 8080:8080
    depends_on:
      - postgres
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: hasurapassword
  us-government-data-migration:
    depends_on:
      - graphql-engine
    build:
      context: infrastructure/
      dockerfile: us-government-data-migration/dockerfile
    links:
      - graphql-engine
    volumes:
     - ./build/us-government-data/:/us-government-data-migration/data
  # next-js-server:
  #   depends_on:
  #     - graphql-engine
  #   links:
  #     - graphql-engine
  #   ports:
  #   - 3000:3000
  #   build: .
volumes:
  db_data: