Description: >
  This template deploys an ECS cluster to the provided VPC and subnets
  using an Auto Scaling Group

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

  ProjectName:
    Type: String
    Default: hasura

  LoadBalancerUrl:
    Type: String
    Description: Application load balancer DNS name

  DomainName:
    Type: String
    Default: usacounts.com
    Description: The DNS name of an existing Amazon Route 53 hosted zone e.g. globalvetlink.com
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid DNS zone name.

Resources:
  WebsiteRecordSet:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Sub ${DomainName}.
      RecordSets:
        - Name: !Sub ${EnvironmentName}-${ProjectName}.${DomainName}
          Type: CNAME
          TTL: '300'
          ResourceRecords:
            - !Ref LoadBalancerUrl

Outputs:
  WebsiteRecordSet:
    Description: WebsiteRecordSet URL
    Value: !Sub https://${EnvironmentName}-${ProjectName}.${DomainName}
    Export:
      Name: !Sub ${AWS::StackName}-WebsiteRecordSet