AWSTemplateFormatVersion: '2010-09-09'

Description: AWS CFN Script that creates an EFS

Parameters:
  EnvironmentName:
    Type: String
  VPC:
    Type: String
  PrivateSubnet1:
    Type: String
  PrivateSubnet2:
    Type: String

Resources:
  EfsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}
        - Key: Project
          Value: !Ref EnvironmentName
      GroupDescription: !Sub Security group for ${EnvironmentName}-Democracy
      GroupName: !Sub ${AWS::StackName}
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - Description: Allow traffic for EFS
          IpProtocol: tcp
          FromPort: 2049
          ToPort: 2049
          CidrIp: 0.0.0.0/0

  EfsFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      FileSystemTags:
        - Key: Name
          Value: !Sub ${AWS::StackName}
        - Key: Project
          Value: !Ref EnvironmentName
      Encrypted: true
      PerformanceMode: generalPurpose

  MountTarget1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EfsFileSystem
      SubnetId: !Ref PrivateSubnet1
      SecurityGroups:
        - !Ref EfsSecurityGroup

  MountTarget2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EfsFileSystem
      SubnetId: !Ref PrivateSubnet2
      SecurityGroups:
        - !Ref EfsSecurityGroup

Outputs:
  EfsSecurityGroup:
    Description: EfsSecurityGroup
    Value: !Ref EfsSecurityGroup

  EfsFileSystem:
    Description: EfsFileSystem
    Value: !Ref EfsFileSystem

  MountTarget1:
    Description: MountTarget1
    Value: !Ref MountTarget1

  MountTarget2:
    Description: MountTarget2
    Value: !Ref MountTarget2
