Description: Create PostgreSQL database server

Parameters:
  DBSubnetGroup:
    Type: String
    Description: Enter a valid DB Subnet Group
    Default: democracy-vpc-rdssubnetgroup-3gakcarf40o3
  DBUsername:
    Type: String
    Description: Enter a valid Database master username
    MinLength: 1
    MaxLength: 16
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    Default: dbadmin
  DBPassword:
    Type: String
    Description: Enter a valid Database master password
    NoEcho: true
    MinLength: 1
    MaxLength: 41
    AllowedPattern: "[a-zA-Z0-9]*"
    Default: dbpAssw0rd
  DBServerSecurityGroup:
    Type: "AWS::EC2::SecurityGroup::Id"
    Description: Enter a valid security group ID for database
  DBInstanceType:
    Type: String
    Description: Enter one of the possible instance type for database
    AllowedValues:
      - db.t2.micro
      - db.t2.small
      - db.t2.medium
      - db.t2.large
    Default: db.t2.small
  EnvironmentName:
    Type: String
    Description: Select the appropriate environment
    AllowedValues: [prod]
    Default: prod

Resources:
  DBServer:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Retain
    UpdateReplacePolicy: Snapshot
    Properties:
      AllocatedStorage: '100'
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      BackupRetentionPeriod: 1
      DBInstanceClass: !Ref DBInstanceType
      DBSubnetGroupName: !Ref DBSubnetGroup
      DBName: postgres
      Engine: postgres
      EngineVersion: '12.4'
      MasterUsername:
        Ref: DBUsername
      MasterUserPassword:
        Ref: DBPassword
      MultiAZ: false
      PubliclyAccessible: false
      StorageType: gp2
      VPCSecurityGroups:
        - Ref: DBServerSecurityGroup
      Tags:
        - Key: Name
          Value:
            Fn::Sub: DBServer-${EnvironmentName}

Outputs:
  DBEndpoint:
      Description: "URL endpoint of database"
      Value:
        Fn::GetAtt: [ DBServer, Endpoint.Address ]