Description: This is an example of a long running ECS service that serves graphql.

Parameters:
  Cluster:
    Description: Please provide the ECS Cluster ID that this service should run on
    Type: String

  GraphqlEndpoint:
    Description: The url of the GraphQL server
    Type: String

Resources:
  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      DesiredCount: 1
      TaskDefinition: !Ref TaskDefinition

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Volumes:
        - Name: us-government-data
          Host:
            SourcePath: /mnt/efs/us-government-data
      ContainerDefinitions:
        - Name: scraper-service
          # Essential: true
          Image:
            Fn::Sub: ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/democracy-scraper:latest
          Memory: 2048
          MountPoints:
            - ContainerPath: /build/us-government-data
              SourceVolume: us-government-data
          PortMappings:
            - ContainerPort: 80
              HostPort: 0
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref CloudWatchLogsGroup
              awslogs-region: !Ref AWS::Region
          Environment:
            - Name: GRAPHQL_ENDPOINT
              Value: !Ref GraphqlEndpoint

  CloudWatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref AWS::StackName
      RetentionInDays: 365
