FROM python:3.9

RUN mkdir -p /app/congress/

# Clone the open source "@unitedstates/congress" XML scrapper
RUN git clone https://github.com/unitedstates/congress.git /app/congress
RUN python3 -m pip install -r /app/congress/requirements.txt

COPY . /app
RUN python3 -m pip install -r /app/requirements.txt

WORKDIR /app
ENTRYPOINT ["python3", "-m", "src.run"]
